name:                notcat
version:             0.1.0.0
github:              Parli/notcat

executables:
  notcat:
    main: Main.hs

dependencies:
- base
- udp-streaming
- streaming
- resourcet
- bytestring

default-extensions:
- OverloadedStrings
- ScopedTypeVariables
